/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArtistSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = ArtistSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthorSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = AuthorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChapterSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'number', 'publishedAt', 'seriesId', 'title', 'updatedAt'] as const
  $columns = ChapterSchema.$columns
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare number: number
  @column.date()
  declare publishedAt: DateTime
  @column()
  declare seriesId: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContentTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = ContentTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GenreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = GenreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeriesSchema extends BaseModel {
  static $columns = ['ageRating', 'alternativeTitles', 'bannerImage', 'contentTypeId', 'coverImage', 'createdAt', 'description', 'featured', 'featuredDescription', 'id', 'keywords', 'publicationYear', 'slug', 'status', 'title', 'translationStatus', 'updatedAt'] as const
  $columns = SeriesSchema.$columns
  @column()
  declare ageRating: string | null
  @column()
  declare alternativeTitles: any
  @column()
  declare bannerImage: string | null
  @column()
  declare contentTypeId: number
  @column()
  declare coverImage: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare featured: boolean
  @column()
  declare featuredDescription: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keywords: any | null
  @column()
  declare publicationYear: number
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare translationStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeriesArtistSchema extends BaseModel {
  static $columns = ['artistId', 'seriesId'] as const
  $columns = SeriesArtistSchema.$columns
  @column()
  declare artistId: number
  @column({ isPrimary: true })
  declare seriesId: number
}

export class SeriesAuthorSchema extends BaseModel {
  static $columns = ['authorId', 'seriesId'] as const
  $columns = SeriesAuthorSchema.$columns
  @column()
  declare authorId: number
  @column({ isPrimary: true })
  declare seriesId: number
}

export class SeriesGenreSchema extends BaseModel {
  static $columns = ['genreId', 'seriesId'] as const
  $columns = SeriesGenreSchema.$columns
  @column()
  declare genreId: number
  @column({ isPrimary: true })
  declare seriesId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
